asp_presentaciones/Pages/Ventanas/Auditorias.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Implementaciones;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentaciones.Pages.Ventanas
{
    public class AuditoriasModel : PageModel
    {
        private IAuditoriasPresentacion? iPresentacion = null;

        public AuditoriasModel(IAuditoriasPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Auditorias();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Auditorias? Actual { get; set; }
        [BindProperty] public Auditorias? Filtro { get; set; }
        [BindProperty] public List<Auditorias>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("NombreUsuario");
                if (!ValidarPermiso())
                {
                   
                    TempData["MensajeError"] = "No tienes permisos para Listar.";
                    return;
                }
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.Entidad = Filtro!.Entidad ?? "";

                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.PorNombre(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Auditorias();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Auditorias>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }

            catch (Exception ex)
            {



                ViewData["MensajeError"] = ex.Message.ToString() + "Debe borrar primero las relaciones que tiene el Artista con otras entidades";

                OnPostBtRefrescar();
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
        public bool ValidarPermiso()
        {
            var variable_session = HttpContext.Session.GetString("NombreUsuario");

            if (string.IsNullOrEmpty(variable_session))
                return false;

            var UsuarioPresentacion = new UsuariosPresentacion();
            var usuarios = UsuarioPresentacion.Listar().Result;

            if (usuarios == null)
                return false;

            var usuario = usuarios.FirstOrDefault(x => x.NombreUsuario.ToLower() == variable_session.ToLower());

            if (usuario == null)
                return false;


            bool Edita = false;
            bool Borra = false;
            bool Nuevo = false;
            bool Listar = false;

            switch (usuario.Rol)
            {
                case 1:
                    Edita = Borra = Nuevo = Listar = true;
                    break;
                case 2:

                    break;
                default:
                    return false;
            }


            return Edita || Borra || Nuevo || Listar;
        }
    }
}

asp_presentaciones/Pages/Ventanas/Carrito.cshtml.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Implementaciones;
using lib_presentaciones.Interfaces;
using lib_presentaciones.models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace asp_presentaciones.Pages.Ventanas
{
    public class CarritoModel : PageModel
    {
        private const string SessionKeyCarrito = "_Carrito";
        public decimal Total => Lista?.Sum(i => i.Cantidad * i.ValorUnitario) ?? 0;

        private readonly ICarritoPresentacion? _carritoService;
        private readonly IDiscosPresentacion? IDiscosPresentacion;
        private readonly IPagosPresentacion? IPagosPresentacion;
        private readonly IFormatosPresentacion? IFormatosPresentacion;
        private readonly IPreciosDiscosPresentacion? IPreciosDiscosPresentacion;



        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public OrdenesDiscos? Actual { get; set; }
        [BindProperty] public Carrito? Filtro { get; set; }
        [BindProperty] public List<Carrito> Lista { get; set; } = new List<Carrito>();
        [BindProperty] public List<Discos> Discos { get; set; }

        [BindProperty] public List<Formatos> Formatos { get; set; }
        [BindProperty] public List<PreciosDiscos> PreciosDiscos { get; set; }
        [BindProperty] public List<Pagos> Pagos { get; set; } = new List<Pagos>();


        [BindProperty]
        public Carrito NuevoItem { get; set; } = new Carrito();
        public bool ItemAgregado { get; set; } = false;


        public CarritoModel(ICarritoPresentacion carritoService, IDiscosPresentacion IDiscosPresentacion, IFormatosPresentacion IFormatosPresentacion, IPreciosDiscosPresentacion IPreciosDiscosPresentacion, IPagosPresentacion IPagosPresentacion)
        {
            this._carritoService = carritoService;
            this.IDiscosPresentacion = IDiscosPresentacion;
            this.IFormatosPresentacion = IFormatosPresentacion;
            this.IPreciosDiscosPresentacion = IPreciosDiscosPresentacion;
            this.IPagosPresentacion = IPagosPresentacion;
        }

        public async Task OnGet(string? disco)
        {
            Lista = ObtenerCarritoSesion();

            Discos = await IDiscosPresentacion!.Listar() ?? new List<Discos>();
            Formatos = await IFormatosPresentacion!.Listar() ?? new List<Formatos>();
            PreciosDiscos = await IPreciosDiscosPresentacion!.Listar() ?? new List<PreciosDiscos>();
            Pagos = await IPagosPresentacion!.Listar() ?? new List<Pagos>();
            if (!string.IsNullOrEmpty(disco))
            {
                NuevoItem = new Carrito();
                var discoEncontrado = Discos.FirstOrDefault(x => x.NombreDisco == disco);
                var discoId = Discos.FirstOrDefault(x => x.Id == discoEncontrado!.Id);

                if (discoEncontrado != null)
                {

                    NuevoItem.Disco = discoEncontrado.NombreDisco;
                    NuevoItem.Formato = 1;
                    NuevoItem.Cantidad = 1;
                    var precioDisco = PreciosDiscos.FirstOrDefault(p => p.Disco == discoId!.Id && p.Formato == NuevoItem.Formato)?.Precio ?? 0;
                    NuevoItem.ValorUnitario = precioDisco;
                }
            }
            else
            {
                ItemAgregado = true;
            }
        }

        public IActionResult OnPostAgregar()
        {
            Lista = ObtenerCarritoSesion();

            if (!ModelState.IsValid)
            {
                Discos = IDiscosPresentacion!.Listar().Result ?? new List<Discos>();
                Formatos = IFormatosPresentacion!.Listar().Result ?? new List<Formatos>();
                Pagos = IPagosPresentacion!.Listar().Result ?? new List<Pagos>();
                ItemAgregado = false;
                return Page();
            }

            AgregarAlCarrito(NuevoItem);
            GuardarCarritoSesion(Lista);

            ItemAgregado = true;

            Discos = IDiscosPresentacion!.Listar().Result ?? new List<Discos>();
            Formatos = IFormatosPresentacion!.Listar().Result ?? new List<Formatos>();
            Pagos = IPagosPresentacion!.Listar().Result ?? new List<Pagos>();

            NuevoItem = new Carrito();

            return Page();
        }
        public IActionResult OnGetIrAlCatalogo()
        {
            return RedirectToPage("/Ventanas/Inicio");

        }

        public IActionResult OnPostEliminar(string discoNom, int formatoId)
        {
            Lista = ObtenerCarritoSesion();
            Lista.RemoveAll(i => i.Disco == discoNom && i.Formato == formatoId);
            GuardarCarritoSesion(Lista);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostFinalizar(string accion, int clienteId, List<string> discosNom, int pagoId)
        {
            Lista = ObtenerCarritoSesion();
            if (accion == "Cancelar")
            {
                Lista.Clear();
                GuardarCarritoSesion(Lista);
                return RedirectToPage("/Ventanas/Inicio");
            }

            if (accion == "Confirmar")
            {
                try
                {
                    await _carritoService!.FinalizarCompra(clienteId, Lista, pagoId);


                    Lista.Clear();
                    GuardarCarritoSesion(Lista);
                    TempData["MensajeExito"] = "Compra realizada exitosamente.";
                }
                catch (Exception ex)
                {
                    TempData["MensajeError"] = ex.Message;
                }

                return RedirectToPage("/Ventanas/Inicio");
            }

            return Page();
        }



        private List<Carrito> ObtenerCarritoSesion()
        {
            var json = HttpContext.Session.GetString(SessionKeyCarrito);
            return !string.IsNullOrEmpty(json)
                ? JsonConvert.DeserializeObject<List<Carrito>>(json) ?? new List<Carrito>()
                : new List<Carrito>();
        }

        private void GuardarCarritoSesion(List<Carrito> carrito)
        {
            var json = JsonConvert.SerializeObject(carrito);
            HttpContext.Session.SetString(SessionKeyCarrito, json);
        }

        private void AgregarAlCarrito(Carrito nuevo)
        {
            var existente = Lista.FirstOrDefault(i => i.Disco == nuevo.Disco && i.Formato == nuevo.Formato);
            if (existente != null)
            {
                existente.Cantidad += nuevo.Cantidad;
            }
            else
            {
                Lista.Add(nuevo);
            }
        }

        public async Task<IActionResult> OnPostBtExportarPDFAsync()
        {
            QuestPDF.Settings.License = LicenseType.Community;


            Lista = ObtenerCarritoSesion();

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Size(PageSizes.A4);

                    page.Header().Text("Listado de Discos").FontSize(20).Bold().AlignCenter();

                    page.Content().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                        });


                        table.Header(header =>
                        {
                            header.Cell().Element(CellStyle).Text("Disco");
                            header.Cell().Element(CellStyle).Text("Formato");
                            header.Cell().Element(CellStyle).Text("Cantidad");
                            header.Cell().Element(CellStyle).Text("Valor unitario");
                            header.Cell().Element(CellStyle).Text("Total");

                            static IContainer CellStyle(IContainer container) =>
                                container.DefaultTextStyle(x => x.SemiBold()).Padding(5).Background("#eee");
                        });


                        foreach (var d in Lista)
                        {
                            table.Cell().Element(CellStyle).Text(d.Disco ?? "");
                            table.Cell().Element(CellStyle).Text(d.Formato.ToString());
                            table.Cell().Element(CellStyle).Text(d.Cantidad.ToString());
                            table.Cell().Element(CellStyle).Text(d.ValorUnitario.ToString("C"));
                            table.Cell().Element(CellStyle).Text((d.Cantidad * d.ValorUnitario).ToString("C"));

                            static IContainer CellStyle(IContainer container) =>
                                container.Padding(5);
                        }
                    });
                });
            });

            using var stream = new MemoryStream();
            document.GeneratePdf(stream);
            stream.Position = 0;

            return File(stream.ToArray(), "application/pdf", "Carrito.pdf");
        }
        public async Task<IActionResult> OnPostBtExportarExcelAsync()
        {
            Lista = ObtenerCarritoSesion();
            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Carrito");


            worksheet.Cell(1, 1).Value = "Disco";
            worksheet.Cell(1, 2).Value = "Formato";
            worksheet.Cell(1, 3).Value = "Cantidad";
            worksheet.Cell(1, 4).Value = "Valor Unitario";
            worksheet.Cell(1, 5).Value = "Subtotal";

            int row = 2;

asp_presentaciones/Pages/Ventanas/Inicio.cshtml.cs
using System;
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentaciones.Pages.Ventanas
{
    public class InicioModel : PageModel
    {
        private IDiscosPresentacion? iPresentacion = null;
        [BindProperty] public List<Discos>? Lista { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }

        public InicioModel(IDiscosPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;



            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
        public async Task<IActionResult> OnGetAsync()
        {
            if (HttpContext.Session.GetString("NombreUsuario") == null)
                return RedirectToPage("/Index");

            Accion = Enumerables.Ventanas.Listas;
            var task =  this.iPresentacion!.Listar();
            task.Wait();
            Lista = task.Result;
            return Page();
        }


        public IActionResult OnPostBtClose()
        {
        
            HttpContext.Session.Clear();
            return RedirectToPage("/Logout");
        }
    }
}

asp_presentaciones/Pages/Ventanas/Carrito.cshtml
@page
@model asp_presentaciones.Pages.Ventanas.CarritoModel
@{
    ViewData["Titulo"] = "Carrito de Compras";
}
<style>
    input.form-control {
        color: black !important;
        background-color: white !important;
    }
</style>

<div class="alert alert-danger">
    "recuerde que debe crear un registro en clientes para poder crear una orden, si ya lo hizo haga caso omiso"
    <br />
    <a href="/ventanas/clientes" class="alert-link">Ir a Clientes</a>
</div>





<h3>Carrito de Compras</h3>
<form method="post" asp-page-handler="BtExportarPDF">
    <input type="submit" value="Exportar a pdf" class="btn btn-secondary" />

</form>
<form method="post" asp-page-handler="BtExportarEXCEL">
    <input type="submit" value="Exportar a excel" class="btn btn-secondary" />

</form>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Disco</th>
            <th>Formato</th>
            <th>Cantidad</th>
            <th>Precio Unitario</th>
            <th>Subtotal</th>
            <th>Acciones</th>
        </tr>

    </thead>


    <tbody>
        @foreach (var carrito in Model.Lista)
        {
            <tr>
                <td>@carrito.Disco</td>
                <td>
                    @{
                        var nombreFormato = Model.Formatos
                        .FirstOrDefault(f => f.Id == carrito.Formato)?.TipoFormato ?? "Formato desconocido";
                    }
                    @nombreFormato
                </td>
                <td>@carrito.Cantidad</td>
                <td>@carrito.ValorUnitario</td>
                <td>@(carrito.Cantidad * carrito.ValorUnitario)</td>
                <td>
                    <form method="post" asp-page-handler="Eliminar">
                        <input type="hidden" name="disco" value="@carrito.Disco" />
                        <input type="hidden" name="formato" value="@carrito.Formato" />
                        <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (!Model.ItemAgregado)
{
    <form method="post" asp-page-handler="Agregar" id="formularioDisco">
        <div class="form-group">
            <label>Disco:</label>
            <input asp-for="NuevoItem.Disco" class="form-control" />
            <span asp-validation-for="NuevoItem.Disco" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Formato:</label>
            <select asp-for="NuevoItem.Formato" class="form-control"
                    asp-items="@(new SelectList(Model.Formatos, "Id", "TipoFormato"))">
            </select>
        </div>
        <div class="form-group">
            <label>Cantidad:</label>
            <input asp-for="NuevoItem.Cantidad" class="form-control" />
            <span asp-validation-for="NuevoItem.Cantidad" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Precio Unitario:</label>
            <input asp-for="NuevoItem.ValorUnitario" class="form-control" readonly />
        </div>
        <button type="submit" class="btn btn-success">Agregar al Carrito</button>
    </form>
}
else
{
    <div class="mt-4">
        <a class="btn btn-primary" asp-page-handler="IrAlCatalogo">Ir al catálogo</a>
    </div>
}

    <h4>Total: @Model.Total.ToString("C")</h4>

    <form method="post" asp-page-handler="Finalizar">
        <div class="form-group">
            <label>Cliente ID:</label>
            <input type="number" name="clienteId" required class="form-control" />
        </div>
        <div class="form-group">
            <label>Método de Pago:</label>
            <select name="pagoId" class="form-control" required>
                <option value="">-- Seleccione método de pago --</option>
                @foreach (var pago in Model.Pagos)
                {
                    <option value="@pago.Id">@pago.TipoPago</option>
                }
            </select>
        </div>
        <div class="form-group mt-3">
            <input type="submit" name="accion" value="Confirmar" class="btn btn-success" />
            <input type="submit" name="accion" value="Cancelar" class="btn btn-danger ml-2" />
        </div>
    </form>

asp_presentaciones/Pages/Ventanas/Discos.cshtml
@page
@model asp_presentaciones.Pages.Ventanas.DiscosModel
@{
    ViewData["Titulo"] = "Discos";
}

<center>
    <div>
        <form method="POST" enctype="multipart/form-data">
            @Html.AntiForgeryToken()

            <div align="left">
                <h3>Discos</h3>
            </div>
            <div align="left" class="bt_panel_buttons">
                <input type="submit" value="Refrescar" asp-page-handler="BtRefrescar" class="btn btn-secondary"
                    disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit" value="Nuevo" asp-page-handler="BtNuevo" class="btn btn-secondary"
                    disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit" value="Guardar" asp-page-handler="BtGuardar" class="btn btn-secondary"
                    disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit" value="Cancelar" asp-page-handler="BtCancelar" class="btn btn-secondary"
                    disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit" value="Exportar a pdf" asp-page-handler="BtExportarPDF" class="btn btn-secondary" />
                <input type="submit" value="Exportar a Excel" asp-page-handler="BtExportarExcel" class="btn btn-secondary" />
            </div>

            @if (Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas || Model.Accion ==
                        lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden" asp-for="@Model.Actual!.Id" />
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden" asp-for="@Model.Actual!.Artista" />
                <input type="hidden" asp-for="@Model.Actual!.Marca" />
                <input type="hidden" asp-for="@Model.Actual!.NombreDisco" />
                <input type="hidden" asp-for="@Model.Actual!.DuracionDisco" />
                <input type="hidden" asp-for="@Model.Actual!.FechaLanzamiento" />
                <input type="hidden" asp-for="@Model.Actual!.Imagen" />
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Editar)
            {
                <div class="containers_vn panel panel-default">
                    <h3>Disco</h3>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Artista</label>
                        <div class="col-lg-6">
                            <select id="nmArtista" class="cts_forms form-control" asp-for="@Model.Actual!.Artista"
                                asp-items="@(new SelectList(Model.Artistas, "Id", "NombreArtista"))"></select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Nombre</label>
                        <div class="col-lg-6">
                            <input id="nmNombreDisco" class="cts_forms form-control" asp-for="@Model.Actual!.NombreDisco" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Marca</label>
                        <div class="col-lg-6">
                            <select id="nmMarca" class="cts_forms form-control" asp-for="@Model.Actual!.Marca"
                                asp-items="@(new SelectList(Model.Marcas, "Id", "NombreMarca"))"></select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Duracion</label>
                        <div class="col-lg-6">
                            <input id="nmDuracionDisco" class="cts_forms form-control"
                                asp-for="@Model.Actual!.DuracionDisco" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Fecha de Lanzamiento</label>
                        <div class="col-lg-6">
                            <input id="nmFechaLanzamiento" class="cts_forms form-control"
                                asp-for="@Model.Actual!.FechaLanzamiento" type="date" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Imagen</label>
                        <div class="col-lg-6">
                            <input id="nmImagen" class="cts_forms form-control" asp-for="@Model.Actual!.Imagen"
                                type="text" />
                        </div>
                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("Mensaje"))
            {
                <input type="hidden" asp-for="@Model.Accion" />
                @await Html.PartialAsync("../Emergentes/Mensajes.cshtml")
            }

            @if (TempData["MensajeError"] != null)
            {
                <div class="alert alert-danger">@TempData["MensajeError"]</div>
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">Mensaje</h2>
                            <h4 align="left">Desea borrar la entidad?</h4>
                            <h6 align="left">@Model.Actual!.NombreDisco, @Model.Actual!.Artista</h6>
                            <br /><br />
                            <input type="submit" value="Borrar" asp-page-handler="BtBorrar" class="btn btn-secondary" />
                            <input type="submit" value="Cerrar" asp-page-handler="BtCancelar" class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("MensajeError"))
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">Mensaje</h2>
                            <h4 align="left">@ViewData["MensajeError"]</h4>
                            <br /><br />
                            <input type="submit" value="Cerrar" asp-page-handler="BtCancelar" class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("MensajeExito"))
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">Mensaje</h2>
                            <h4 align="left">@ViewData["MensajeExito"]</h4>
                            <br /><br />
                            <input type="submit" value="Cerrar" asp-page-handler="BtCancelar" class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas || Model.Accion ==
                        lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input id="flNombre" class="cts_forms form-control" asp-for="@Model.Filtro!.NombreDisco"
                    placeholder="Nombre" />
                <br />
                <div class="containers_vn panel panel-default">
                    <table class="tb_data table table-striped table-bordered table-hover">
                        <tr>
                            <th>Artista</th>
                            <th>Marca</th>
                            <th class="cl_hidden">NombreDisco</th>
                            <th class="cl_actions">DuracionDisco</th>
                            <th class="cl_actions">FechaLanzamiento</th>
                            <th class="cl_actions">Imagen</th>
                            <th class="cl_actions">Accion</th>
                        </tr>
                        @if (Model != null && Model.Lista != null)
                        {
                            @foreach (var elemento in Model.Lista)
                            {
                                <tr>
                                    <td>@elemento._Artista!.NombreArtista</td>
                                    <td>@elemento._Marca!.NombreMarca</td>
                                    <td class="cl_hidden">@elemento.NombreDisco</td>
                                    <td class="cl_hidden">@elemento.DuracionDisco</td>
                                    <td class="cl_hidden">@elemento.FechaLanzamiento</td>
                                    <td class="cl_hidden">@elemento.Imagen</td>
                                    <td>
                                        <input type="submit" value="Modificar" asp-page-handler="BtModificar"
                                            class="btn btn-secondary" asp-route-data="@elemento.Id" />
                                        <input type="submit" value="Borrar" asp-page-handler="BtBorrarVal" class="btn btn-secondary"
                                            asp-route-data="@elemento.Id" />
                                        
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            }
        </form>
    </div>
</center>